### ISSUE TITLE
SALMON and DEMONS study enhancements

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#128]
including:
- minute support for random trigger windows
- specific time triggers
- layout enhancements
- label sliders

@predictive-technology-laboratory/owners

**Comment by MatthewGerber** [comment]
@wesbonelli I've created a new branch for this work:  salmon-demons-study-enhancements

Please make commits to this branch within your repository and submit a pull request when ready. Please follow [the coding conventions](https://github.com/predictive-technology-laboratory/sensus/wiki/Developing-Sensus#coding-conventions).

Thanks!

**Comment by wesbonelli** [comment]
The pull request is ready to go.

**Comment by wesbonelli** [comment]
@predictive-technology-laboratory/owners The changes are ready.
