### ISSUE TITLE
Add push notifications to ping participant phones.

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#130]

**Comment by MatthewGerber** [comment]
Related to #329.

**Comment by MatthewGerber** [comment]
Then create a simple web view that allows us to view the pending notifications for all users in a study. Would be very handy for monitoring and addressing issues (e.g., by contacting subjects with no notifications scheduled).

**Comment by jtb8vm** [comment]
**The guide wants us to set up a backend first, but another approach could allow us to focus on testing directly from Notification Hub without having to deploy anything**

I am following "[Sending Push Notifications from Azure Mobile Apps](https://developer.xamarin.com/guides/xamarin-forms/cloud-services/push-notifications/azure/)" from the Xamarin Developer Guide, but this approach requires a backend that is already running and configured to work with the Notification Hub. After reading more documentation, it seems we may be able to test notifications directly from the Notification Hub without having to focus on the backend choice right away. 

According to the guide, the steps to integrate Notification Hub with a Xamarin.Forms app are: 

- The Xamarin.Forms application registers with the PNS, which returns a handle.
- The Azure Mobile Apps instance sends a notification to its Azure Notification Hub, specifying the handle of the device to be targeted.
- The Azure Notification Hub sends the notification to the appropriate PNS for the device.
- The PNS sends the notification to the specified device.
- The Xamarin.Forms application processes the notification and displays it.

![image](https://user-images.githubusercontent.com/9642167/36230414-59355992-11a8-11e8-9d3b-efa2dda164a4.png)

The guide wants us to configure the server project to work with Notification Hub, which would force us to deploy an Azure App Services project. After digging around, I saw Xamarin University's [tutorial](https://www.youtube.com/watch?v=le2lDY22xwM), uses an approach where we would first get a successful notification sent directly from the Notification Hub without worrying about the Azure Mobile App backend. The steps for this approach would be : 

- configure the google FCM (Firebase Cloud Messaging) : android
- configure the APNS (Apple PNS) : iOS
- configure other platforms, if needed : UWP, etc.
- send a notification from Azure Notif Hub and test that we can receive natively
- move onto configuring the backend

Would the second approach be better for where we're at? We can touch bases on this more tomorrow, too. Thanks for reading this essay!!

**Comment by MatthewGerber** [comment]
@jtb8vm Yes, the second approach (testing the hub-PNS-device pathway before incorporating back-end) seems like the appropriate place to start.

**Comment by jtb8vm** [comment]
Cool-- I will work in that direction. I will try to get us as close as
possible with the FCM and APNS setup, we still good for 4pm today?

Best,
Jordan

**Comment by MatthewGerber** [comment]
Yes, 4pm.

**Comment by jtb8vm** [comment]
Firebase Cloud Messaging (FCM) Android notification setup.
---
**First Steps:**
- Create Google FCM project (requires Google account) NOTE: Ensure package names in dev env match those in FCM project
- Create Azure Notification Hub project + namespace (requires Azure account)
- Grab FCM server key and plug into Azure notification hub
- Add nuget packages to android project in VS / XS, includes:
   - Xamarin.Firebase.Messaging
   - Xamarin.GooglePlayServices.Base (already installed)
- Download google-services.json file from Google FCM console, add to Android project
- Change properties of google-services.json file to have build action of `GoogleServicesJson`
- Add [required configuration](https://developer.xamarin.com/guides/android/data-and-cloud-services/google-messaging/remote-notifications-with-fcm/) to Android-Manifest.xml NOTE: need "ApplicationId"
- above is committed to branch "azure-notifications"

**Next Steps:** 
- Implement Firebase Instance ID service for device registration
- Log the Notification data, test notifs for background tasks

**Comment by jtb8vm** [comment]
Baseline implementation is committed. 
We register the device with FCM in `FirebaseIIDService.cs`, then handle incoming/outgoing messages in `FirebaseMessagingService.cs`. I was able to send / receive data and log it to the application output:

![image](https://user-images.githubusercontent.com/9642167/36400852-81f044b2-15a1-11e8-9efa-cc633fc51a60.png)

The token is generated by the Firebase IID Service (in this case my emulator). Then, the Firebase Messaging Service prints out the payload:

![image](https://user-images.githubusercontent.com/9642167/36400868-9b88f68a-15a1-11e8-817d-437f7d46b8c6.png)

There is also a warning about a missing analytics library. This makes sense, as in the FCM console I can't see whether or not the message went through. For next steps I will add these analytics, and then we can move onto triggering events.

**Comment by MatthewGerber** [comment]
Excellent. Is this going from FCM->device or Azure->FCM->device?

**Comment by jtb8vm** [comment]
Hi Prof. G,

For now it's just FCM->device, but to get Azure involved we just need to
put the notification into JSON-form. I'll take a look at that today! I also
want to make sure the Firebase Analytics are working, I haven't been able
to see any results in the FCM console. Then after that we can discuss event
triggering?

Best,
Jordan

**Comment by MatthewGerber** [comment]
Sounds good.

**Comment by jtb8vm** [comment]
Just got a successful 201 Message Sent using the Notification Hub REST API:

![image](https://user-images.githubusercontent.com/9642167/36614547-1505e58e-18ab-11e8-8ba6-8c581d32c95a.png)

I was able to follow [this documentation](https://msdn.microsoft.com/en-us/library/azure/mt608572.aspx) about directly sending notifications to a device by id. You can also send [batch](https://msdn.microsoft.com/en-us/library/azure/mt734910.aspx) notifications. The steps are simply: generate SAS token, format the POST request, and send. In this example, I used Postman to send a notification and was able to receive it locally for my android emulator. I followed [this](https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token) to generate a SAS for use with notification hubs.

**Comment by MatthewGerber** [comment]
Great. Looks like we're getting close to integration. Let's meet soon to
discuss integration.

**Comment by jtb8vm** [comment]
Moving forward with integration, setup steps are documented [here](https://github.com/jtb8vm/sensus/wiki/Sensus-Notification-Notes).
