### ISSUE TITLE
Add a way to filter out missed calls when telephony metadata is a trigger condition?

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#148]
When "Idle" is used, scripts trigger when a call was outgoing but did not connect and also when incoming and missed. Modified in the Sensus build being used for SALMON and DEMONS as a separate trigger condition, which filters out calls shorter than some X number of seconds.

**Comment by MatthewGerber** [comment]
@wesbonelli Created a new branch (demons) for this work. Submit a PR against this branch.

**Comment by wesbonelli** [comment]
@MatthewGerber Submitted the pull request.
