### ISSUE TITLE
Android telephony probe can fail to trigger script

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#171]
Not sure of cause. Error message is: System.NullReferenceException: Object reference not set to an instance of an object

Stack trace:

SensusService.Probes.User.ScriptRunner.<ScriptRunner>c__AnonStorey0.<>m__0(object oo, Tuple<_,_> previousCurrentDatum)
SensusService.Probes.Probe.set_MostRecentDatum(Datum value)
SensusService.Probes.Probe.StoreDatum(Datum datum)
SensusService.Probes.ListeningProbe.StoreDatum(Datum datum)
Sensus.Android.Probes.Communication.AndroidTelephonyProbe.<AndroidTelephonyProbe>m__0(object sender, string outgoingNumber)
Sensus.Android.Probes.Communication.AndroidTelephonyOutgoingBroadcastReceiver.OnReceive(Context context, Intent intent)
Android.Content.BroadcastReceiver.n_OnReceive_Landroid_content_Context_Landroid_content_Intent_(IntPtr jnienv, IntPtr native__this, IntPtr native_context, IntPtr native_intent)
at (wrapper dynamic-method) System.Object:1284f271-da73-4cb2-a627-048ee8a82189 (intptr,intptr,intptr,intptr)

**Comment by MatthewGerber** [comment]
What was the exception message?

**Comment by wesbonelli** [comment]
Meant to include that as well. System.NullReferenceException: Object reference not set to an instance of an object

**Comment by MatthewGerber** [comment]
What version of the app generated this exception?

**Comment by wesbonelli** [comment]
I think it was 9.0.0. The crash report was dated Apr. 19.

**Comment by MatthewGerber** [comment]
The crash report should also list a Sensus version number, which could be
different than the version that was current as of Apr. 19. Do you have a
version number for the crash or just the date?

**Comment by wesbonelli** [comment]
Ok, I found the version numbers for this issue and the S3 one. Both are 9.0.0.

**Comment by MatthewGerber** [comment]
I'm looking at the code for 9.0.0 and I cannot see how this would happen. If you want to track this down you will need to check out the code associated with this release (check out the 9.0.0 tag):

https://github.com/predictive-technology-laboratory/sensus/releases/tag/Sensus-v9.0.0

Then build and reproduce the error. It's coming from the Android telephony probe.

**Comment by MatthewGerber** [comment]
Closing this for now. Let's see if it shows up in Insights for the latest release.
