### ISSUE TITLE
Crash reports related to S3 upload failure

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#172]
Several different stack traces below.

System.IO.IOExceptionError writing request:

System.Net.WebConnectionStream.EndWrite(IAsyncResult r)
System.IO.Stream.<BeginEndWriteAsync>m__8(Stream stream, IAsyncResult asyncResult)
System.Func<Stream, IAsyncResult, VoidTaskResult>.invoke_TResult_T1_T2(Stream, IAsyncResult)(wrapper delegate-invoke)
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<_,_,_> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)
System.IO.Stream.CopyToAsyncInternal()
System.Net.Http.HttpClientHandler.SendAsync()
System.Net.Http.HttpClient.SendAsyncWorker()
Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext()
Amazon.Runtime.Internal.HttpHandler<TRequestContent>.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.RedirectHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ResponseHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7<T>.MoveNext()
Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1<T>.MoveNext()

Amazon.S3.AmazonS3ExceptionThe difference between the request time and the current time is too large:

Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
Amazon.Runtime.Internal.ExceptionHandler<T>.Handle(IExecutionContext executionContext, Exception exception)
Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7<T>.MoveNext()
Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1<T>.MoveNext()

Amazon.Runtime.AmazonServiceExceptionA WebException with status SendFailure was thrown:

Amazon.Runtime.Internal.WebExceptionHandler.HandleException(IExecutionContext executionContext, WebException exception)
Amazon.Runtime.Internal.ExceptionHandler<T>.Handle(IExecutionContext executionContext, Exception exception)
Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7<T>.MoveNext()
Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1<T>.MoveNext()

and

Amazon.Runtime.Internal.WebExceptionHandler.HandleException(IExecutionContext executionContext, WebException exception)
Amazon.Runtime.Internal.ExceptionHandler<T>.Handle(IExecutionContext executionContext, Exception exception)
Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7<T>.MoveNext()
Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.CognitoIdentity.CognitoAWSCredentials.<GetPoolCredentialsAsync>d__59.MoveNext()
Amazon.CognitoIdentity.CognitoAWSCredentials.<GenerateNewCredentialsAsync>d__57.MoveNext()
Amazon.Runtime.RefreshingAWSCredentials.<GetCredentialsAsync>d__8.MoveNext()
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7<T>.MoveNext()
Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1<T>.MoveNext()

System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Sockets.Network-Stream':

System.Net.WebConnectionStream.EndWrite(IAsyncResult r)
System.IO.Stream.<BeginEndWriteAsync>m__8(Stream stream, IAsyncResult asyncResult)
System.Func<Stream, IAsyncResult, VoidTaskResult>.invoke_TResult_T1_T2(Stream, IAsyncResult)(wrapper delegate-invoke)
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<_,_,_> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)
System.IO.Stream.CopyToAsyncInternal()
System.Net.Http.HttpClientHandler.SendAsync()
System.Net.Http.HttpClient.SendAsyncWorker()
Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext()
Amazon.Runtime.Internal.HttpHandler<TRequestContent>.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.RedirectHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ResponseHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7<T>.MoveNext()
Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9<T>.MoveNext()
Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__1<T>.MoveNext()
Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5<T>.MoveNext()
Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1<T>.MoveNext()

**Comment by MatthewGerber** [comment]
What versions of Sensus did you see these for? I believe they're all fixed
in the most recent release in the app stores.

**Comment by wesbonelli** [comment]
Participants updated on Apr. 6, so these would all have been on 9.0.0.

**Comment by MatthewGerber** [comment]
I thought I fixed this prior to 9.0.0. Can you reproduce the error on your device using the current version?

**Comment by MatthewGerber** [comment]
Closing this for now. See if you can reproduce it in the current release.
