### ISSUE TITLE
Create GUI protocol generator

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#185]
Probably add a GUI .NET or Mac project to the Sensus solution that references the shared SensusService code base.

**Comment by MatthewGerber** [comment]
@wesbonelli We could also try these options for a GUI protocol designer. The Chrome extension looks promising.

http://www.extremetech.com/computing/83812-run-android-apps-on-your-windows-pc-2

**Comment by wesbonelli** [comment]
@MatthewGerber Mobizen was buggy for me but I got an alternative called AirDroid working. It offers both screen mirroring and typing-only access to Android phones. Again, maybe not a long term solution, but it will probably work for our studies this semester.
