### ISSUE TITLE
iOS can fail to upload data when Display Participation is selected

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#189]
Seems to occur when the local data store has grown very large, but need to double check if only happens in this case. Stays on the "Please Wait" page indefinitely, often crashes if not canceled.

**Comment by MatthewGerber** [comment]
Fixed with d22c679acc374f55415f0af93b93d71afda5e18e. But we still need to make data stores more robust to large accumulations of data. See Issue #190.
