### ISSUE TITLE
Need to display progress when committing data on iOS

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#193]

**Comment by MatthewGerber** [comment]
@wesbonelli After you finish the callback delay merge, would you mind taking a look at this? On iOS, when the remote data store is executed there is no visual feedback as to what is happening with the upload. We need a page that pops up and displays a progress bar indicating progress uploading the data and allowing the user to cancel the operation. You can take a look at how I do this for sharing the local data store for an example.

**Comment by wesbonelli** [comment]
@MatthewGerber Sure, I'll take a look. Do we need this for iOS only?

**Comment by MatthewGerber** [comment]
Yes, this is iOS only. It's not an issue with Android because everything
happens in the background there.

Matt

**Comment by wesbonelli** [comment]
Oh, right. There's no user interaction for this on Android. Sounds good.

**Comment by wesbonelli** [comment]
This is almost done.

Is it possible to trigger a page navigation from non-UI code? I'm not able to reference `Xamaran.Forms.Navigation` from any class not in `Sensus.UI`. For now I have a Commit option on `RemoteDataStorePage` analogous to the Share option on `LocalDataStorePage`.

**Comment by MatthewGerber** [comment]
I'm not exactly sure what you want to do, but I think you might be able to
do something similar to what's done in
AppDelegate.ReceivedLocalNotification where it navigates to a new page if
needed. A Commit button the remote data store won't work for several
reasons.
