### ISSUE TITLE
Add compression to transfer of JSON

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#199]

**Comment by wesbonelli** [comment]
I've added this to S3 Remote Data Store w/ an on/off option. It zips the json string just before committing it. How should I proceed? And would it be worthwhile to do this in the local data store too, in order to keep local memory costs down?

**Comment by MatthewGerber** [comment]
Go ahead and create a PR into develop for this. Let's hold off on the local data store for now.
