### ISSUE TITLE
Add an option to generate a SQL database schema from data types

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#205]
Would it be helpful to allow the user to choose which types are included, with an "include all" option? The only use case I can think of is if a user wanted to create a database tailored to an individual protocol or study, though I'm not sure what the benefit of doing that might be.

using version 9.7.1
OS: both

**Comment by MatthewGerber** [comment]
I don't think this is necessary. As long as you have a tool in the dashboard project that generates a schema from the C# code, we should be set. I don't think this needs to be exposed via the app. If you think of a different use case post it here and we can discuss.
