### ISSUE TITLE
Can we trigger GPS reading upon activation by significant change listener on iOS?

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#216]
Also consider background app refresh.

**Comment by MatthewGerber** [comment]
@wesbonelli This is what we were discussing today.

**Comment by wesbonelli** [comment]
@MatthewGerber Since we're using it to wake the app up and not specifically for location services, should this be implemented in SensusServiceHelper?

**Comment by MatthewGerber** [comment]
It seems like this capability should apply to all polling probes on iOS.
How about adding a property named SignificantChangePoll to the PollingProbe
class (iOS only via compiler directives). If set to true the PollingProbe
would listen for significant changes and execute a poll on each change.

**Comment by wesbonelli** [comment]
@MatthewGerber Should this override the existing polling interval? For instance if the probe is set to poll every 5 minutes but SignificantChangePoll is set to true, should the probe only poll when significant change prompts it to?

**Comment by MatthewGerber** [comment]
You could add two options, one to turn on significant change polling and a
second to override (if true) or complement (if false) the scheduled poll. I
think this should cover all use cases but give it some thought.

**Comment by wesbonelli** [comment]
@MatthewGerber We may have to rethink this a bit. I've finished this and tested it, and though it works fine for detecting location change, it doesn't seem to allow us to harness the 15-minute wakeup. [This forum post](https://forums.developer.apple.com/thread/48029) appears to confirm that unless the user is moving and location is changing, we can't use this to run our own code. It does restart the app if it's crashed or the user has killed it, though, even when stationary- it doesn't bring it to the foreground but notifications are generated- so I still think it's worth adding?

**Comment by MatthewGerber** [comment]
So are you saying that significant change updates are not delivered if the
user is not moving?

**Comment by wesbonelli** [comment]
Yes, exactly. Also, what I said about it waking the app up may not be true. I think that was just a callback scheduled before the app was killed.

**Comment by wesbonelli** [comment]
Turns out it was just a callback.

**Comment by MatthewGerber** [comment]
Completed by 6f24bc82d78a09fb2f819c74c08534c10450b8b1.
