### ISSUE TITLE
Add option to cancel any scripts waiting for a response when a window ends

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#218]
Version: 9.8.1
OS: both (iOS may not be trivial)

**Comment by MatthewGerber** [comment]
@wesbonelli I'm working on some changes that will affect this. Hold off for now.

**Comment by wesbonelli** [comment]
@MatthewGerber Ok just let me know when I should take a look at it.

**Comment by MatthewGerber** [comment]
Closed with previous merges.
