### ISSUE TITLE
Should we add an option to try to submit script data immediately after a script is completed?

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#219]
v9.8.1
both OS

Probably best if Remote Data Store upload settings took precedence over a setting like this. Prof. Barnes and I discussed this today and thought it may help limit the risk of losing data. Does this seem like a good idea?

**Comment by MatthewGerber** [comment]
Sounds reasonable. You could add an on/off option to the script probe to trigger a local data store commit after responses have been received. This would put responses into non-volatile storage immediately (assuming a file local data store), safeguarding against app crash, device restart, battery loss, etc. Pushing to remote would only safeguard against things like file corruption, which aren't likely. Feel free to add this to develop and PR from there.

**Comment by wesbonelli** [comment]
@MatthewGerber I just looked into it and I think it already commits to the local data store immediately after a script is finished; I didn't realize this. From the `Run` method in `ScriptRunner`:

            Task.Run(async () =>
            {
                // geotag the script-run datum if any of the input groups are also geotagged. if none of the groups are geotagged, then
                // it wouldn't make sense to gather location data from a user.
                double? latitude = null;
                double? longitude = null;
                DateTimeOffset? locationTimestamp = null;
                if (script.InputGroups.Any(inputGroup => inputGroup.Geotag))
                {
                    try
                    {
                        Position currentPosition = GpsReceiver.Get().GetReading(default(CancellationToken));

                        if (currentPosition == null)
                            throw new Exception("GPS receiver returned null position.");

                        latitude = currentPosition.Latitude;
                        longitude = currentPosition.Longitude;
                        locationTimestamp = currentPosition.Timestamp;
                    }
                    catch (Exception ex)
                    {
                        SensusServiceHelper.Get().Logger.Log("Failed to get position for script-run datum:  " + ex.Message, LoggingLevel.Normal, GetType());
                    }
                }

                await _probe.StoreDatumAsync(new ScriptRunDatum(runTime, _script.Id, _name, script.Id, script.CurrentDatum?.Id, latitude, longitude, locationTimestamp), default(CancellationToken));
            });

`StoreDatumAsync` then calls `LocalDataStore.AddAsync`. Running it in the debugger confirms it happens pretty much immediately. Should we close the issue?

**Comment by MatthewGerber** [comment]
You're right that it adds it to the local data store immediately, but
that's in memory initially. The commit to local file only happens
periodically determined by the data store delay or when enough data
accumulate in memory. If an app crash or device reboot intervenes then
you'd lose what's in memory. I don't think this is a substantial risk, but
if you see cases where this is a problem then we can consider a fix.

**Comment by wesbonelli** [comment]
Ok- that makes sense, thanks.

**Comment by wesbonelli** [comment]
I've PR'd this into ptl-develop.
