### ISSUE TITLE
collect submission timestamp when the submit button is hit.

### ISSUE THREAD

**Issue by cadancai** [predictive-technology-laboratory/sensus#226]
We need this information for the response time of the prompt/survey.

**Comment by MatthewGerber** [comment]
Added by https://github.com/predictive-technology-laboratory/sensus/commit/24fb3183c3200f8f6b97a3dd8a95cb362d8977f0. 

Note:  If you are interested in calculating response time, I'm not sure the submission time for the whole survey is the right time to look at. For example, suppose a survey is generated at time 0 and that the user completes a particular question (e.g., text box) at time 30. The user then proceeds through the rest of the survey and submits everything at time 600. What is the response time for the text box? I think it would be 30 (`Timestamp`) and not 600 (`SubmissionTimestamp`). You need a clear rationale for selecting between these.
