### ISSUE TITLE
Run-on-start doesn't work on 10-beta iOS

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#234]
Probes-Script interaction-RunOnStart on iOS doesn't work: no prompt after restarting the protocol.
This same function works on Android.

**Comment by MatthewGerber** [comment]
Did you check the surveys screen to make sure it's not there? The surveys
no longer pop up automatically, even on start.

**Comment by haunthy** [comment]
Yes, I did check 'Take Surveys' tray. No prompt is listed there.

**Comment by MatthewGerber** [comment]
Can you please send me the protocol?

**Comment by haunthy** [comment]
I double checked the protocol, It was because only the probe is enbaled but the inputgroup is not.. Sorry about it. It works now.
