### ISSUE TITLE
Will scheduled protocol starts/stops work properly across time zones?

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#248]

**Comment by clmckinley** [comment]
@MatthewGerber It depends on what you mean by work appropriately.  What they do is store the DateTime (without timezone) to start and then compare that with the current phone datetime also without timezone. 
 
This will cause the protocol to start at the time set regardless of timezone.  For instance if you set it at 9AM then it will start at 9AM local time for each phone.  This means that someone in London (+1) will start 5 hours earlier than someone in Charlottesville (-4).

**Comment by MatthewGerber** [comment]
Sounds good. Thanks.
