### ISSUE TITLE
InputGroup.IncompleteSubmissionMessage will not always behave as anticipated.

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#249]

**Comment by wesbonelli** [comment]
Is this related to my changes?

**Comment by MatthewGerber** [comment]
Yes but nothing serious. I think what could happen is that the parameter is passed in as null but the input group has a message on it. This should be displayed but wouldn't be.

**Comment by MatthewGerber** [comment]
@wesbonelli Looks like you removed your changes for this. Right?

**Comment by wesbonelli** [comment]
Yes. I think I'll have the chance to look at it again this weekend and rework them.
