### ISSUE TITLE
Add protocol settings to disable notifications at night/during specific time windows?

### ISSUE THREAD

**Issue by wesbonelli** [predictive-technology-laboratory/sensus#253]
Suggested by Dr. Barnes in response to a study participant's feedback.

In most cases I think turning on Do Not Disturb or Airplane Mode would take care of this, but there could be cases where a user may not want to rely on those for some reason and this would be useful.

**Comment by MatthewGerber** [comment]
@wesbonelli I think there's an easy fix for this. We could add a `NotificationSoundExclusionWindows` property to `Protocol`, similar to what we do with random windows. If a notification delivery time falls within one of these windows, don't play a sound or vibrate. There are options for sound/vibrate in the iOS and Android notifiers. Want to take a stab at this?

**Comment by wesbonelli** [comment]
@MatthewGerber Sure, I can work on this. I'll take a look at it when I'm back in town.

**Comment by MatthewGerber** [comment]
Addressed by #326.
