### ISSUE TITLE
NextScheduleWindowMinExpiration

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#256]
<img width="432" alt="screen shot 2016-10-12 at 11 55 42 pm" src="https://cloud.githubusercontent.com/assets/4643066/19336215/9b8eda50-90d7-11e6-9e2c-91200cfb7d32.png">

I've seen this fail on Android as well. Does not happen each time.

**Comment by mrucker** [comment]
Yeah, it's a poorly written test and something we need to look into. Has to do with the time stamps not always being exact in our logic. I think we're using DateTime.Now to check if a date is right. Depending on how long it takes the unit test to run that value can change.
