### ISSUE TITLE
Move Android probes into shared project

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#269]
iOS probes are currently shared, and cross-platform deserialization assumes that the namespaces for each probe's class are the same between Android and iOS.

**Comment by MatthewGerber** [comment]
Turns out this will be quite difficult. An easier solution would be to eliminate `Shared` from all namespaces.

**Comment by mrucker** [comment]
ahh... Nice catch. The commit looks good to me. I'd love if we could get the protocols to be more "backwards" compatible.

**Comment by MatthewGerber** [comment]
Agreed, it's too easy to break backwards compatibility when serializing protocols the way we do. We could keep version IDs in the protocols and write JSON transformations to handle version changes...or something else. Issue #271.
