### ISSUE TITLE
Concurrent unit test failing

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#275]
@mrucker 

Can you take a look at the attached on iOS 10? It doesn't happen every time. I suspect that the task.Wait call is running on the main thread, thus blocking the two calls to ExecuteThreadSafe, which are competing for access to the main thread. So I think it's maybe a flaw in the test.

![img_0065](https://cloud.githubusercontent.com/assets/4643066/19843411/8dcf3674-9ef8-11e6-93e6-7a29f330d4d2.PNG)

**Comment by mrucker** [comment]
Hmm... Yeah, I'll look into it today and let you know what I find.

**Comment by mrucker** [comment]
Alright,

I've got it fixed but I can't do a pull request on GitHub right now. I keep
getting a 500 error for some reason. I'll try again tomorrow.
