### ISSUE TITLE
Sampling function is not gathering data evenly

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#288]
Probes->"Max Data/Second".

If Max Data/Second=1 (1Hz), most of the data are 1000ms apart from each other, some are 2000ms apart.

If Max Data/Second=8 (1Hz),the time gaps between data points collected are like (in ms):
2
1
1
2
1
1
992

**Comment by MatthewGerber** [comment]
Should be fixed by 05af73aebd2d53ec5e2cef152215bfb5d1c9c741.
