### ISSUE TITLE
Notification but no surveys, on both iOS and Andorid

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#289]
Both iOS and Android users reported:

They can receive notifications, but when they click it and go to Sensus, there's no survey listed there. 

Some users also reported they didn't even receive notifications for a whole day.

When they are led to Sensus, sometimes they saw Sensus started loading (which means it crashed before), sometimes that can immediately see the "Manage my studies" page.

Here're some original quotes from the users' description: 

" As far as today goes, I received one notification for a survey this afternoon, but upon opening it there were no surveys to take. Other than that I received no other surveys." --- Android 6.0.1

"My study is running I have checked, but I still am hardly receiving any surveys, and I check my phone frequently so it's unlikely that I am missing all of them." -- Android

"I'm pretty diligent about keeping Sensus open and I know that I try to take the survey before the time that the notification says it expires. I click the notification and then it takes me directly to the "pending surveys" page but there's no survey there. " --iOS 10.0.2

"I receive notifications regularly throughout the day, but when I open my phone to complete the survey, there is no survey presented under the "Take Surveys" option on the main page of the application. I find this to be the case in probably 80% of the cases in which I receive a notification for a new survey. After I clear the notification after not being able to take the survey, I receive several new notifications, sometimes up to eight within a five minute period of time, none of which are presented on the "Pending Surveys" page." -- iOS 9.3.2

**Comment by MatthewGerber** [comment]
In this log, here's an example :
a survey was scheduled at: [ScriptRunner] Scheduled for 11/14/2016 3:46:51 PM (1f4e7f95-8a4b-45dd-ad75-2437a3a5a44e)

But at 3:47pm when user clicked the notification it seems Sensus restarted:

11/14/2016 3:47:47 PM:  [iOSSensusServiceHelper] Log file started at "/var/mobile/Containers/Data/Application/3F72131F-AC86-4624-99FC-0A87D3C8505A/Documents/sensus_log.txt".

This is the only log file I have so far. But probably Sensus 13.0 has some crashing problem remained.

[0 (5).txt](https://github.com/predictive-technology-laboratory/sensus/files/600012/0.5.txt)

**Comment by MatthewGerber** [comment]
This is probably more common a problem when only using surveys and not doing any background processing, as the system is more likely to kill the app in such cases. Might be able to fix by storing the object/method name in the notification and using that as the basis for executing the callback.

**Comment by haunthy** [comment]
But all the participants are also running accelerometer and GPS probes on the background at the same time. But one thing for sure, this didn't happen to all of the participants cause I do have some who have it work well. But it happened to a fair amount of people.

**Comment by MatthewGerber** [comment]
Good to know. That should reduce the likelihood of the app being killed.

**Comment by MatthewGerber** [comment]
I think this problem is largely addressed by recent commits.
