### ISSUE TITLE
@Capstone - Need the read.json function to handle incomplete json files in sensusR

### ISSUE THREAD

**Issue by brendobendo** [predictive-technology-laboratory/sensus#290]
Answer the following questions depending on the type of issue you are submitting.

# For All Issues

### Which version of Sensus are you currently using?
N/A - this is a sensusR issue

### Which operating system(s) does this issue involve (Android, iOS, or both)?
Mac but this applies for PCs too. 

# For Enhancement Issues

### What would you like SensusR to do that it does not already do?
Occasionally, I've come across incomplete json files coming from AWS (perhaps due to how AWS splits up the json files). Specifically, the last json record is truncated and there is no ending bracket (]). When the r function tries to read in these files, the following error occurs: 

Error: parse error: premature EOF                                        [ {"$type":"Sensus.Probes.User.                      (right here) ------^. 

I have recreated the issue removing the ending bracket from an otherwise valid json file. 
Don't know how widespread this issue is but it would be great to avoid fixing the files manually.

**Comment by MatthewGerber** [comment]
@brendobendo Can you send me one of the compressed files from AWS that look like this?

**Comment by brendobendo** [comment]
Here's the one that was giving me trouble
[sample_data.json.zip](https://github.com/predictive-technology-laboratory/sensus/files/615440/sample_data.json.zip)

**Comment by MatthewGerber** [comment]
@brendobendo Can you give me access to the S3 bucket so that I can look at the data there?

**Comment by MatthewGerber** [comment]
@brendobendo Can you give me access to the S3 bucket so that I can look at the data there?
