### ISSUE TITLE
@Capstone - can't export local data properly from iOS protocols

### ISSUE THREAD

**Issue by brendobendo** [predictive-technology-laboratory/sensus#315]
### Which version of Sensus are you currently using?
13.1.1

### Which operating system(s) does this issue involve (Android, iOS, or both)?
iOS

### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.

When I to send myself local data from a protocol, it compresses the data but saves the attachment as a json file. So when I try to open this file, I see a bunch of gibberish because the the compressed file is trying to be read as a json file. I've tried saving the attachment as a compressed file (tar.gz), but that doesn't work. I've found a workaround with my droid by saving the file to my drive with the tar.gz extension but haven't found a similar solution for iOS app since you can't choose how to share the file. So in short, the problem would be solved if the data file was attached as a compressed folder by default.

**Comment by wesbonelli** [comment]
The current Sensus release is 13.1.0.

Using that version, I tried to reproduce what you described on both Android and iOS without success. When I navigate to Local Data Store, select Share and email it to myself, I get a .zip file attachment. To clarify, you received a .json file when you did this?

**Comment by MatthewGerber** [comment]
@brendobendo I am seeing the same thing (no problems) as @wesbonelli. I've tried this on Sensus 13.1.0 on iPhone 5 (10.2) and Android 6. I've tested the file local data store and the RAM local data store. I always get a .zip file when I share the resulting local data store.

Can you please share your protocol with us privately so we can test it?

**Comment by brendobendo** [comment]
Never mind. I tried exporting my protocol again today and it saved as a zip. The issue happened about a week ago (when I emailed you about opening the compressed file). I must have been running an older version of sensus at the time or something. Sorry about that and thanks for looking into this guys.

**Comment by MatthewGerber** [comment]
@brendobendo It just occurred to me what probably happened here. I think you probably shared the protocol itself rather than the local data store. These are distinct sharing operations, and the former produces a .json file (the protocol definition) that is encrypted. This is why you could not open the shared .json file and saw gibberish on your screen when you opened it.
