### ISSUE TITLE
Add protocol testing to XTC

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#327]
@mrucker Looks like we can add multiple project/app references to the Sensus.Tests.Cloud project (e1c416e421a93597af236c863ef0f9bb89a616ef). I think this will be the way we bring back protocol UI testing to the XTC as we discussed recently. This will complement what we're doing with running unit tests on the XTC.

Can you take a look sometime? Not a big rush, but will be nice.

**Comment by mrucker** [comment]
Yeah, totally. I'll add it to my list for some afternoon when I'm schooled/researched out.

**Comment by jtb8vm** [comment]
Hi all, I'm currently looking into:
- "Continuous Integration (CI) workflow that automatically submits new application builds to Xamarin Test Cloud when code changes are checked in" from <a href="https://developer.xamarin.com/guides/testcloud/introduction-to-test-cloud/">Xamarin</a>

- Adding <a href="https://developer.xamarin.com/guides/testcloud/uitest/working-with/submitting-tests-to-xamarin-test-cloud/"> UI Tests </a>

Is there any way I could be added to the organization in order to run these tests?  Otherwise I can set up another independent organization for my own testing purposes.  Thanks.

**Comment by MatthewGerber** [comment]
I've added you to our XTC account. Once you're familiar with building, deploying, and testing Sensus we should talk about our approach to XTC integration.

**Comment by jtb8vm** [comment]
Moving into summer mode! I'm working more with XTC and am getting more comfortable with the testing process-- would it be worthwhile to set up a [wiki ](https://github.com/jtb8vm/sensus/wiki/Using-Xamarin-Test-Cloud-with-Sensus)to document some steps involved? 

This might help to make sure I'm getting it right while also providing a tool to get more people up to speed in the future.  I can create an issue for constructing this documentation, or perhaps we can keep the discussion flowing here?  My first step in the process would be ensuring all of the proper nuget packages are installed.  One could document this process like:

In order to perform UITests, ensure the Nuget package `Xamarin.UITest` is installed.
![xtc 1a](https://cloud.githubusercontent.com/assets/9642167/26464647/88454698-4156-11e7-8776-687d631cd7c0.png)
 
(to be cont'd)

**Comment by jtb8vm** [comment]
Hi all,

Currently working towards an automated deployment to XTC on a commit to git.  After discussing with Prof. Gerber, the flow should look something like:

- Commit to git
- Continuous Integration step (Travis CI or other tool, integrated with Git)
- Within CI Environment:
   - Execute automated deployment to XTC (`mono ... asubmit ... `) 
   - Use pre-defined device lists for XTC: tailor towards students, university-wide, businesses, etc.
   - Tests passed? <--- get results

**Comment by MatthewGerber** [comment]
@jtb8vm Good start! Some refinements:

- Commit to git:  This will be a commit to a special branch, to be named "xtc"
- Continuous integration:  Take a look at the GitHub-recommended CI environments and select the one that seems best suited to our purposes.
- Within the CI environment:
  - The XTC deployment should use a flexible approach to device and OS targeting. I can envision pushing a commit to the xtc branch with a text file named "targets" that contains all of the devices/OSs to run on within the XTC. The content of this file will be tailored to whatever Sensus-based study is upcoming. For example, if we were about to use Sensus on a student population, the file would contain the primary iPhone and iOS versions in use by the target student population, along with Android as XTC budgets allow (few students run Android).
  - Don't forget that we have two XTC apps in mind:  The NUnit app (traditional unit testing) and the Sensus app (UI testing). The former will simply require a check on the number of test run and passed (we already do this). The latter contains no unit tests; instead, its success will be measured in terms of data being collected from the devices. The ideal way to take this measurement is to allow the Sensus UI test to complete on XTC and then (within the CI environment) analyze the data that were collected by Sensus and uploaded to AWS S3. For example, if the Sensus UI test turns on the GPS polling probe at 10-second intervals and runs for 100 seconds, then you should find 10 GPS readings in AWS S3 upon completion of the XTC test run. Make sense?

**Comment by jtb8vm** [comment]
From Xamarin's [Intro to Continuous Integration](https://developer.xamarin.com/guides/cross-platform/ci/intro_to_ci/):

"If you use Jenkins to build your apps, you can store your code in Visual Studio Team Services or Team Foundation Server and continue to use Jenkins for your CI builds. You can trigger a Jenkins build when you push code to your team project's Git repository or when you check code in to TFVC [Team Foundation Version Control]"

![image](https://user-images.githubusercontent.com/9642167/27300976-9f8bc82e-54ff-11e7-87f5-dac18efd7359.png)

After reading up on some CI workflows, it looks like using [Visual Studio Team Services](https://www.visualstudio.com/team-services/) (VSTS) in conjunction with Git would allow us to:
- use an externally-hosted Build Server on VSTS (don't need a dedicated Mac to host, and has a free version we can play around with)
- trigger a Jenkins build on a push to the Sensus Git repository

Then from Jenkins, we can use shell commands to deploy our tests to the Xamarin Test Cloud, for more see:
- [Using Jenkins with Xamarin](https://developer.xamarin.com/guides/cross-platform/ci/jenkins_walkthrough/)
- [Jenkins with Visual Studio Team Services](https://www.visualstudio.com/en-us/docs/marketplace/integrate/service-hooks/services/jenkins)
- [Submitting UITests at the Command Line](https://developer.xamarin.com/guides/testcloud/uitest/working-with/submitting-tests-at-command-line/)

It might also be possible to execute this same workflow with [Travis CI](https://travis-ci.org/), though there is no explicit documentation on how to deploy to the XTC from a Travis CI server.  For the purposes of getting it up and running, Jenkins will probably be easiest. We could also opt to host a private build server running Jenkins ready to Build and deploy to XTC on a Git commit, but the Team Foundation Server can do the same without the hardware requirements.

**Comment by MatthewGerber** [comment]
Looks good! Let's go with the Jenkins approach that you outline.

**Comment by jtb8vm** [comment]
It looks like the Team Foundation Server (TFS) only acts as a CI server, and has a plugin for Jenkins which must be hosted on another Build Server.  So, Visual Studio Team Foundation Server can't act as our Build Server.  At this point I think it'd be easier to not have to depend on Visual Studio Team Services or TFS, and to just go with Git and another externally hosted Build Server to do Jenkins builds. OpenShift 3 from Red Hat has a free tier that I've been playing around with to [externally host Jenkins on](https://blog.openshift.com/pipelines-with-jenkins-2-on-openshift/).  Using this, our CI workflow would look like:

![image](https://user-images.githubusercontent.com/9642167/27440387-989e582a-5738-11e7-926a-5bcaec71b541.png)

**Comment by MatthewGerber** [comment]
That sounds even better. I was wondering myself what value VSTS and TFS add, so if we can eliminate them and go with a simpler setup that'd be nice.

**Comment by jtb8vm** [comment]
Quick status update-- In moving forward with setting up the [Build Server in RedHat OpenShift](https://blog.openshift.com/pipelines-with-jenkins-2-on-openshift/), I ran into a hiccup where we need more space than the free tier provides.  Below is a screenshot of the OpenShift Dashboard, where the cloud-based application (Pod) is stuck in a crash loop.  There is 1GB allowed storage within the free tier application, and this Jenkins template Pod was only supposed to take up ~500MB. I tried to create an application with no initial claims to persistent memory, and still ran into this error.  Unfortunately the Logs (not pictured) do not say much, the Exit code 137 Out Of Memory (circled below) is really the only revealing detail.  

While using RedHat I found it fairly easy to set up projects both with the Web Application GUI and the Command Line. You simply login, create a project, define a deployment configuration (can easily pull these from git), and deploy the pod. The downsides came with the lack of transparency and documentation once I ran into errors.  

It might be worthwhile investing in a higher tier, _or_ for now I am looking into this nifty [Jenkins on Google Container Engine](https://cloud.google.com/solutions/jenkins-on-container-engine) article, which also has really good documentation and a free trial to mess around with.  I have a good feeling about this one, and will let you guys know how it goes.  

![oom](https://user-images.githubusercontent.com/9642167/27553239-2b60d9ac-5a78-11e7-98a7-2d29c9445d88.png)

**Comment by MatthewGerber** [comment]
thanks for the update. is it possible to run the build server in a
free-tier EC2 instance?

**Comment by jtb8vm** [comment]
Yes that is entirely possible, the monthly cost if we were to leave it running would be ~90$.  I'll get started with this QuickStart.

![aws jenkins](https://user-images.githubusercontent.com/9642167/27555674-a12faa3e-5a80-11e7-943c-3eb8026e683e.png)

**Comment by MatthewGerber** [comment]
I like how this looks. Let me know what you find out.

**Comment by jtb8vm** [comment]
Today I messed around with getting [Jenkins set up on an EC2 server on AWS](https://d0.awsstatic.com/Projects/P5505030/aws-project_Jenkins-build-server.pdf).  My steps were:

- Create a group within Amazon's Identity Access Manager ([IAM](https://aws.amazon.com/iam/)): named `sensus-ci`
- Create an IAM admin user for myself with root access / privileges 
- Create a keypair to share between the EC2 instance and myself for connecting through SSH
- Create an Amazon Virtual Private Cloud ([VPC](https://aws.amazon.com/vpc/)) to act as a private network through which to communicate
- Create a security group defining access rights to the server (SSH allowed only on my IP, HTTP & HTTPS allowed for all IPs)
- Launch the EC2 server instance and connect through SSH client in Terminal
- Use `wget` to download the Jenkins repository and `install` to set it up

So at this point I have Jenkins running on the Amazon EC2 server and am configuring it to work with Git.  There is one blocker-- when I try to access the jenkins server like `<public_DNS>:port`, I get an error 503: service unavailable.  I'm thinking I either misconfigured the EC2 instance, need a different version of Jenkins, or Jenkins does not have what it needs in the EC2 environment (maybe missing a dependency). I'll keep working on it, but so far even with this hiccup AWS has my vote over RedHat OpenShift.

**Comment by MatthewGerber** [comment]
Sounds like you're close! The problem sounds like a network or firewall
issue. Is Jenkins listening on the instance's public IP address, and is the
firewall configured to allow traffic in on this address?

**Comment by jtb8vm** [comment]
Thanks! Jenkins is up!
![screen shot 2017-06-29 at 1 12 22 pm](https://user-images.githubusercontent.com/9642167/27700779-a88eafc0-5ccc-11e7-8054-a7d160aa6c05.png)

**Comment by MatthewGerber** [comment]
Nice!
