### ISSUE TITLE
Capstone - Connect to Estimote Bluetooth beacon

### ISSUE THREAD

**Issue by ckohout** [predictive-technology-laboratory/sensus#328]
### Which version of Sensus are you currently using?
for any version
### Which operating system(s) does this issue involve (Android, iOS, or both)?
Both
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
We need to know if the phone is within range of a beacon. Below are links to the APIs for iOS and Android.
iOS: http://developer.estimote.com/ibeacon/tutorial/part-1-setting-up/
Android: http://developer.estimote.com/android/tutorial/part-1-setting-up/

**Comment by MatthewGerber** [comment]
@ckohout Let me know when the beacons arrive.

**Comment by ckohout** [comment]
@MatthewGerber I have the beacons, I can bring them to your office sometime tomorrow.

**Comment by MatthewGerber** [comment]
I won't be in my office tomorrow (Monday). Can you bring them by Tuesday
morning? Have you completed the range measurements yet for the various
power settings?

**Comment by ckohout** [comment]
I have class Tuesday morning but I can drop them off at 12:15 or 1:45.

**Comment by MatthewGerber** [comment]
12:15 or shortly after will be fine.

**Comment by MatthewGerber** [comment]
Closed by PR #339.
