### ISSUE TITLE
Sampling rate issue with Band probes-unevenly sampling

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#341]
For band probes (MicrosoftBandAcc, MicrosoftBandGyro),
Probes->"Max Data/Second".

If Max Data/Second=1 (1Hz), most of the data are 1000ms apart from each other, some are 2000ms apart.

If Max Data/Second=8 (1Hz),the time gaps between data points collected are like (in ms):
2
1
1
2
1
1
992

**Comment by MatthewGerber** [comment]
Which version of Sensus is this for?

Did you mean "8 (8Hz)"?

Can you submit the actual JSON for these readings?

**Comment by haunthy** [comment]
Yes I mean 8Hz, sorry for the typo. 
here's one json accelerometer data set 

[MicrosoftBandAccelerometerDatum.zip](https://github.com/predictive-technology-laboratory/sensus/files/814267/MicrosoftBandAccelerometerDatum.zip)

**Comment by MatthewGerber** [comment]
I plotted the CDF of the inter-reading times in R:

```
sensus.decompress.json("~/Desktop/MicrosoftBandAccelerometerDatum")
data = sensus.read.json("~/Desktop/MicrosoftBandAccelerometerDatum")
lags = diff(data$MicrosoftBandAccelerometerDatum$Timestamp)
lag.ecdf = ecdf(as.numeric(lags))
num.rows = nrow(data$MicrosoftBandAccelerometerDatum)
plot(lag.ecdf, xlim = c(0,0.7), xlab = "Inter-reading time (seconds)", ylab = "Percentile", main = paste("Inter-reading times (n=", num.rows, ")", sep = ""))
abline(h = 0.93, lty = 2)
abline(v = 1/8, lty = 2)
```

And here's what I got:

![inter-reading_cdf](https://cloud.githubusercontent.com/assets/4643066/23518171/948f5932-ff40-11e6-865c-9b93dc5d1dd2.png)

Looks like we're at 93% by the desired 0.125 lag, and we approach 100% by 0.5-0.6 seconds.

This isn't dramatically different from what I'd expect. Do you think it's causing issues?

**Comment by MatthewGerber** [comment]
@haunthy I've added the time lag CDF calculation (shown above) to SensusR via c50a37fe9e87f8fe782145adceca21f62e1ea365. This will not yet be in the R CRAN package repository, but you can build the package from source after downloading it from GitHub. Here's what we had planned to do:

* Check the device accelerometer to confirm that the CDF aligns with the expected sampling rate.
* Check the Band accelerometer in the same way, duplicating the above results.
* Figure out if (and why) we're getting "clumped" data from the Band.

**Comment by MatthewGerber** [comment]
@haunthy If you decide to use SensusR to investigate this, you can follow the instructions [here](https://github.com/predictive-technology-laboratory/sensus/wiki/SensusR). The source package that you need is [here](https://github.com/predictive-technology-laboratory/sensus/raw/develop/SensusR/Releases/SensusR_2.1.0.tar.gz).

**Comment by haunthy** [comment]
I just checked the phone's accelerometer probe: The sampling rate is not even too....

So our guess yesterday is not completely right (we thought this bug only happened in the band probes).

Now the problem is clear:
Both the smartphone and band probe have this sampling rate issue. I'm wondering if you have successfully committed that fix after I tested your diawi link last semester.

**Comment by MatthewGerber** [comment]
A fix is forthcoming... Tonight sometime.

**Comment by MatthewGerber** [comment]
I added the new sampler via 8e56b34345c828d880dfe62e2f07caa963437d61. I am attaching sampled accelerometer data at 1Hz, 8Hz, and 32Hz, along with the CDF for the lags. These should be more consistent; however, it's impossible to get perfect sample spacing. Let me know if you see issues like you saw before. I'll send you Diawi links so you can test on your devices and with the Band. Please post back confirming the fix.

[SamplerData.zip](https://github.com/predictive-technology-laboratory/sensus/files/818416/SamplerData.zip)

**Comment by MatthewGerber** [comment]
Here's a sample of Band accelerometer data at 8Hz, too. It also looks better.

[band.zip](https://github.com/predictive-technology-laboratory/sensus/files/818423/band.zip)

**Comment by MatthewGerber** [comment]
Re-open if needed.
