### ISSUE TITLE
inputID and GroupID  being copied too while a script question is copied

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#342]
When create script interaction in a protocol, every time you copy a question, the input ID and group ID are also copied. 

This happened to both iOS and Android.  

Why don't we just add a new field called InputGroupName that shows the input  group name when people make a question?

**Comment by MatthewGerber** [comment]
Should be fixed by 4d62a16439bc7b523904f754660987f6424bc796.

**Comment by MatthewGerber** [comment]
@haunthy Can you reproduce this in 13.3.0?
