### ISSUE TITLE
Add Bluetooth proximity probe to iOS

### ISSUE THREAD

**Issue by cw9dd** [predictive-technology-laboratory/sensus#353]
### Which version of Sensus are you currently using?
13.3.0

### Which operating system(s) does this issue involve (Android, iOS, or both)?
iOS 

### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
Add Bluetooth proximity probe to iOS.

**Comment by MatthewGerber** [comment]
This won't be possible for our pilot. See #354.
