### ISSUE TITLE
Devise + Automate XTC tests for use with Sensus-CI (Jenkins on Amazon EC2)

### ISSUE THREAD

**Issue by jtb8vm** [predictive-technology-laboratory/sensus#355]
#### Devising & Automating XTC tests for use with Sensus-CI (Jenkins on Amazon EC2)

Hi all, I'm currently finishing up connecting EC2 to Git, and once we have this pipeline / trigger set up we can trigger the XTC build on a push to a branch `xtc`.

On the test-writing side of things, I was thinking of a potential approach that I wanted to run by you guys @MatthewGerber @mrucker.  Would it be possible to use two separate Test Cloud Projects, one for the `Sensus.*.Tests` and one for the `Sensus.*` projects?  That way we wouldn't have to use compiler directives to try and detect these unit tests versus normal apps.  We could simply devise two separate deploys with each Test Cloud Project handling each one individually.  It would look something like:

![xtc](https://user-images.githubusercontent.com/9642167/27934684-d6610346-6274-11e7-8bb2-923750f7b89a.png)

We could simply deploy two separate apps to XTC from Jenkins to perform Unit vs. UITests. This would be just two separate Mono commands in the Jenkins server. Let me know what you guys think!

**Comment by MatthewGerber** [comment]
Nice figure.

I think this makes sense. Our Sensus.Tests.Cloud project currently deploys either Sensus.iOS.Tests or Sensus.Android.Tests to XTC. These are both NUnit test suites, and they can remain the same. At some point I think I'd like to rename this project to Sensus.Cloud.UnitTests, but you don't need to do this.

It should be straightforward to add a new project named Sensus.Cloud.UiTests that does UI testing specifically for Sensus protocols that will be deployed in upcoming studies. This is what is missing from our current NUnit test suites.

@mrucker Does this make sense?

@jtb8vm As long as Mark doesn't see any obvious problems, go ahead with this.

**Comment by mrucker** [comment]
Sorry for the delay in responding to this. I got a little distracted at the
end of last week with some other Sensus stuff.

This seems reasonable to me.

Prof. Gerber,

If you want me to work with Jordan at any point this summer to rename or
reorganize or renaming some of our projects in Sensus just let give the
word. As long as you guys know what you want it should be fairly easy with
my refactoring tools. Also, I know we've talked about it a little but it
seems like we keep getting distracted.

**Comment by jtb8vm** [comment]
I have the Jenkins server up and running at http://ec2-34-213-3-86.us-west-2.compute.amazonaws.com:8080, configured now to work with the primary Sensus repo and targeting the `ui-testing` branch. Here is a sample output of a build job in Jenkins:

![image](https://user-images.githubusercontent.com/9642167/31319633-1a2bbc74-ac35-11e7-83c2-0174d69bd9ca.png)

Currently I just have it echoing some text, but now am moving onto the automation step using `mono` to deploy some XTC tests. I have documented some steps for setting this up [here](https://github.com/jtb8vm/sensus/wiki/Actually-Setting-up-a-Jenkins-CI-Server-for-use-with-Git-on-Amazon-EC2)
