### ISSUE TITLE
Add day-of-week specifier for scripted probes

### ISSUE THREAD

**Issue by cw9dd** [predictive-technology-laboratory/sensus#359]
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
Add day-of-week specifier for scripted probes. Currently scripted probes that are less frequent than daily can only be scheduled by the frequency (e.g., every 5 days).

**Comment by MatthewGerber** [comment]
Please add to the milestone.

**Comment by cw9dd** [comment]
I didn't forget but I can't seem to do that. I don't see a checkbox before each issue; could this be an authority problem?

**Comment by MatthewGerber** [comment]
Ah, okay. I'll add them.
