### ISSUE TITLE
Facebook status

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#368]
for indicators of affect, activity, etc. this might already come through the facebook probe. will need to check.

**Comment by MatthewGerber** [comment]
Similar to #350. Can do this periodically outside of Sensus.

**Comment by cw9dd** [comment]
After some research, it seems the most straightforward way is to have each participant download Facebook activity through the "download archive" service from the website (which is what Yu did in her study). Data types in the resulting data set are listed here: http://www.idownloadblog.com/2016/01/18/how-to-download-facebook-archive/. The resulting data set contains VERY personal information (e.g., content of private messages).

Alternatively, python scripts (https://github.com/RaghavSood/FBMessageScraper) are written to scrape Facebook message history (which is part of the archive download mentioned above). The scripts require a range of parameters obtainable from a participant's Facebook message page. Also, this blog post (http://minimaxir.com/2015/07/facebook-scraper) teaches how to scrape status posts from Facebook pages (applicability to personal accounts not certain). 

It does not seem we can just pull metadata from someone's Facebook activity; data obtained will contain content information.
