### ISSUE TITLE
UITesting: Compiler Directives for linking to Calabash

### ISSUE THREAD

**Issue by jtb8vm** [predictive-technology-laboratory/sensus#380]
**Quick summary:**
How best do we link Calabash to the Sensus.iOS and Sensus.Android projects through compiler directives?  (some new considerations with latest VS) 

---
Currently trying to debug some UiTests after the latest pull. First things first, I want to ensure I'm properly linking with the Calabash framework.  Out of the box (after my [latest pull](https://github.com/jtb8vm/sensus/commit/a111dd218a227bf4655c5713ae8d8215d4a1d380)), Sensus.iOS and Sensus.XTC.UiTests build without errors.  When I go to run the UI Tests locally for iOS, I get the following error (in both iOS tests, second one removed for brevity):

`SetUp : System.Exception : Unable to contact test backend running in app. A common cause is that the app is not properly linked with Calabash. Please verify that it includes the Calabash component.`

I noticed we have a `UI_TESTING` compiler directive defined that for me is never being hit in `Sensus.iOS.AppDelegate`:

```
#if UI_TESTING
                Forms.ViewInitialized += (sender, e) =>
                {
                    if (!string.IsNullOrWhiteSpace(e.View.StyleId))
                        e.NativeView.AccessibilityIdentifier = e.View.StyleId;
                };

                Calabash.Start();
#endif
```
I'm guessing I would need to define that UI_TESTING compiler directive myself?  Also-- I poked around and found [this article](https://developer.xamarin.com/guides/testcloud/uitest/cheatsheet/) where they mention that the "Newer version of Visual Studio for Mac and Visual Studio provide the `ENABLE_TEST_CLOUD` compiler directive to prevent the Calabash DLL from being included in the released version of the application."  

Once the Calabash instance can start, the tests can run and though they don't succeed out of the box they can at least finish. With Xamarin Studio I was not able to get this far, so I should be good to at least write tests and perform them locally.  Let me know if you guys have any thoughts on the `(UI_TESTING || ENABLE_TEST_CLOUD)` directive issue. Thanks!

**Comment by MatthewGerber** [comment]
I think you've figured it out. Just replace UI_TESTING with ENABLE_TEST_CLOUD in all places, since these variables have the same purpose and the latter is included by default. You can search for all occurrences of UI_TESTING by running `grep -r 'UI_TESTING' .` in the top-level Sensus directoy.

**Comment by jtb8vm** [comment]
Thanks! I was also able to do within VS Search--> Replace in Files... , and have switched the UI_TESTING compiler directive to ENABLE_TEST_CLOUD for my fork. The UITests run, but fail `WaitingForElement([unknown])` which I'm confident will be an easy fix.

I ran into one recurring error with the DeviceAgent (iOS Application Runner for Simulator), where it's not able to launch.  I found that if you just remove the Sensus and Device Agent currently installed on the simulator, the tests can run without the Device Agent error. Going forward I'll be checking in as the tests develop and I'll be sure to log any blockers.

**Comment by MatthewGerber** [comment]
You'll still want to grep because visual studio will only search source
files. It will miss many other files.

**Comment by jtb8vm** [comment]
We have been refactored, PR is in now.
I've closed the PR so that we can talk about how we want to handle merging my contributions in. Maybe we could have specific branches for issues that I work on, then you can review and merge into develop when the time comes?  For this I would need write access to the repository, and I believe I will also need this for setup with the AWS Jenkins server.  Let me know what you think, Thanks!
