### ISSUE TITLE
UITests: General

### ISSUE THREAD

**Issue by jtb8vm** [predictive-technology-laboratory/sensus#384]
---
Hi all,

Here I'm documenting some UITest work. As of now we have a collection of UITests that are to some extent fragile and have not been running locally for me. My process has been:

- pull down latest from PTL and confirm everything builds without error (some warnings)

- Run UITests (out of the box)
     - fail with Calabash linkage error (wondering if this has anything to do with this first screen: 

![screen shot 2017-08-22 at 1 22 39 pm](https://user-images.githubusercontent.com/9642167/29579696-90694014-8741-11e7-98f0-591c0db4f88b.png)

- should I be updating any packages here or do we need to keep any particular older versions of packages?

- Once I acknowledge the above, I'm able to link to Calabash (that error seems to be either obligatory and/or a one-off) but then I run into a new set of errors, my guess is from reconciling newer and older versions of XTC.  @mrucker would you be free sometime this week to go over our current UITests?

**Comment by MatthewGerber** [comment]
I don't think it's related to the screenshot above.

**Comment by jtb8vm** [comment]
Okay, let me know if there are any particular updates to dependencies that need to be made.

I am back in the swing of things now that classes have started, so I will be checking in more frequently with updates.

**Comment by jtb8vm** [comment]
Hi all,

Looking more deeply into the UiTesting approach, I realized that my Sensus.iOS app is crashing when it tries to run the UiTesting Protocol. Maybe the protocol definition is missing? Perhaps I need to supply the UiTesting definitions via JSON to this shell script? `~/SensusWorkspace/sensus/Sensus.XTC.UiTests/Protocols/PromptForUnitTestingProtocol.sh`

**Comment by MatthewGerber** [comment]
you're on the right track! keep at it...

**Comment by jtb8vm** [comment]
After meeting with Mark, he pointed out there is a potential issue with the UiTestingProtocol, and supplying its JSON definition to `Sensus.XTC.UiTests/Protocols/PromptForUnitTestingProtocol.sh`. The latest version is missing the JSON, and since it was written a few months ago it will most likely be in some sort of disagreement with the current Protocol structure. So we are going to dig up that old JSON, I'll tweak it for a first round of tests, and we'll see if that fixes it. Thanks guys!

**Comment by MatthewGerber** [comment]
This isn't the right way to go, at least if I'm understanding your
proposal. You should create a testing protocol using a newly compiled
version of the Sensus app (with no ENCRYPTION_KEY set
SensusServiceHelper.cs). Share this protocol with yourself (e.g., via email
attachment) from the Sensus app. Once you have this protocol file, you
should use it as the UiTestingProtocol.

**Comment by MatthewGerber** [comment]
Done with UI testing updates for now. Will revisit this if needed.
