### ISSUE TITLE
Email study contact doesn't work from protocol page on iOS

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#387]

**Comment by jtb8vm** [comment]
I can help debug this if it's still open-- I need to be able to share my protocol from iPhone to do UITesting. Looks like the Send button might just be accidentally disabled?

![image](https://user-images.githubusercontent.com/9642167/30074209-a94e934c-923e-11e7-9de7-1c3b8306833e.png)

**Comment by MatthewGerber** [comment]
Seems to work fine now.
