### ISSUE TITLE
Potential problematic behavior of Bluetooth probe

### ISSUE THREAD

**Issue by cw9dd** [predictive-technology-laboratory/sensus#390]
Encounters between two devices (one iOS, one Android) recorded every ~15 minutes for many consecutive hours; in reality the two devices were not in proximity for the majority of those times detected

**Comment by MatthewGerber** [comment]
Please post the raw JSON data.

**Comment by cw9dd** [comment]
https://www.dropbox.com/sh/brnwgr1qwsn5s34/AABBZqfgpcV9QzpWrvYwafIHa?dl=1
