### ISSUE TITLE
Integrate with Visual Studio app center.

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#401]

**Comment by jtb8vm** [comment]
Jumping on this now !! First step is to add the app center SDK, going to see if I can get this to build.

**Comment by jtb8vm** [comment]
Still attempting to get Android/iOS projects to build in App Center, just need to get configurations working.
![image](https://user-images.githubusercontent.com/9642167/35186947-86d65030-fdea-11e7-8a2d-99dbc2ad7577.png)
