### ISSUE TITLE
Dashboard to monitor the collected data

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#406]
The aim of the dashboard is to monitor the collected data in real time. This can help researchers better cope with missing data ( due to low compliance, app not running, bugs, etc. )

**Comment by MatthewGerber** [comment]
Closely related to #130, as the push notification architecture will afford much of the data that needs to be visualized in the dashboard.

**Comment by MatthewGerber** [comment]
Also related to #329.

**Comment by MatthewGerber** [comment]
@cadancai This is related to your dashboard effort on EIM. Can you please talk with @Boukhechba about this? I don't think this entails much work beyond what you are already planning to do.
