### ISSUE TITLE
Improve the process of creating a protocol

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#407]
Creating a protocol on a computer is much "user friendly" than on a mobile phone, specially for protocols including active sensing. Creating a web app to create and manage protocols can help significantly.

**Comment by MatthewGerber** [comment]
@Boukhechba This is a top priority. Can you and Shabnam book a meeting with me to discuss/plan?

https://matthew-gerber.youcanbook.me/
