### ISSUE TITLE
Monitoring protocols

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#408]
The way Sensus is dealing with launching protocols is a little bit problematic. From my experience, we experienced a lot of issues in downloading the protocol and opening it using sensus for IOS participants, updating a protocol is also an issue. I think a better way would be to centralise the monitoring of the protocols in a given study as follows:

1- The study designer starts by creating a protocol using Sensus Web Dashboard (that needs to be created). Once done, he will get a protocol code (e.g. ADGYE89). 

 2-Rather than downloading a .json protocol file on a user's phone, the participant will only introduce the protocol code sent by the study designer (ADGYE89), then the protocol will be loaded automatically (A simple SQL query to retrieve the json data associated with this protocol code).

3- The study designer can change/update a protocol using Sensus Web Dashboard. Then, the protocol will be automatically  updated on the participants phones.

**Comment by MatthewGerber** [comment]
Related to #407 and #406.

**Comment by MatthewGerber** [comment]
This has been addressed with the addition of the authentication service within Sensus. The dashboard would need to be enhanced accordingly.
