### ISSUE TITLE
Sensus crashes when turning the Sound Probe on  

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#432]
### Which version of Sensus are you currently using?
15.0.0

### Which operating system(s) does this issue involve (Android, iOS, or both)?
Android

### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.

Sensus crashes when turning the sound Probe on

**Comment by MatthewGerber** [comment]
Confirmed on iOS.
