### ISSUE TITLE
Add support for other remote data stores

### ISSUE THREAD

**Issue by dibyadas** [predictive-technology-laboratory/sensus#437]
Google drive is a good option for a data store. The GDrive API can be used to upload the data.
Also, is there a reason why only Amazon S3 bucket has been implemented?

**Comment by MatthewGerber** [comment]
GDrive is a decent idea. You're welcome to implement this if you wish.

AWS S3 is easy to use, scalable, secure, etc. We haven't found a better alternative.

**Comment by MatthewGerber** [comment]
Not planning to expand remote data storage beyond S3 at this time. Feel free to submit PR with your own implementation, and we will add it.
