### ISSUE TITLE
Encrypt protocols produced by designer

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#438]
All sensus protocol .json files are encrypted to protect sensitive data they might contain. The web designer also needs to encrypt the .json files that it produces. You can obtain a 256-bit key with the following command:

    openssl enc -aes-256-cbc -k secret -P -md sha1

I think you can use [this](http://php.net/manual/en/function.openssl-encrypt.php) PHP method to encrypt prior to the S3 put operation, using `aes-256-cbc` as the method.

In the UI, simply include fields on the first page for the AES key and initialization vectors, as output by the above command. Use these values in your PHP function to encrypt the .json file prior to S3 put.

**Comment by Boukhechba** [comment]
Done

**Comment by MatthewGerber** [comment]
Can you PR this to me?

**Comment by MatthewGerber** [comment]
@Boukhechba Can you PR this to me?
