### ISSUE TITLE
QR code not working

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#511]
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.

Adding a study using a QR code is currently not working.

**Comment by MatthewGerber** [comment]
@Boukhechba It works fine for me. 

I cannot fix this without more detail. Which QR code? What's the content of the QR code? How did you create it? What's the error, if any? etc...

**Comment by MatthewGerber** [comment]
Note that QR codes must now have specific [prefixes](https://predictive-technology-laboratory.github.io/sensus/api/Sensus.QrCodePrefix.html)

This is probably your issue. The content of the QR code must be `sensus-protocol:url` -- and if you are using a Dropbox URL it must end with `dl=1`.

**Comment by Boukhechba** [comment]
Oh you are right. I wasn't aware of that. Thanks @MatthewGerber
