### ISSUE TITLE
Add PID before starting the protocol 

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#512]
Add a text input to introduce PID before launching a protocol.

**Comment by MatthewGerber** [comment]
@Boukhechba Do you mean that you'd like to be able to edit the text that currently reads "To participate in this study as described above, ..." ?

**Comment by Boukhechba** [comment]
Well, we don't have that text in the current version. The current text says: This study will start immediately and continue...The following data will be collected: .... Then submit.
I think we need to have an input before the submit button that allows participants to identify their selfs (can be a number e.g. 0001)

**Comment by MatthewGerber** [comment]
@Boukhechba Version 15.6.0 provides this capability. Edit the confirmation mode in the protocol, and see the documentation [here](https://predictive-technology-laboratory.github.io/sensus/api/Sensus.ProtocolStartConfirmationMode.html).
