### ISSUE TITLE
Add polling calendar probe for Android

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#523]
https://developer.android.com/guide/topics/providers/calendar-provider

**Comment by clmckinley** [comment]
@MatthewGerber What do you want to record with this probe?  For instance, do you want:
all events in the calendar, all future events, just the next event, etc.

also assuming i can determine the main calendar do you just want that or do you want all calendars?

**Comment by MatthewGerber** [comment]
Let's discuss before doing this.

**Comment by MatthewGerber** [comment]
Putting this off. Would be better done on a backend server.
