### ISSUE TITLE
Failed survey submission. Additional fields appearing.

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#549]
One participant was unable to submit a survey. The app said he did not complete all the fields but he did. He also noticed that each time he tapped Submit the number of "Other" field increased by 1 in a picker page question (see attached screenshot).

https://mail.google.com/mail/u/0/#inbox/FMfcgxvwzJBlWjPlmtkfBKDtwjJPvTTh

**Comment by clmckinley** [comment]
@MatthewGerber The linked file does not work.

**Comment by MatthewGerber** [comment]
The link is to my email, which you cannot access for privacy reasons. I'll need to send it via email.

**Comment by clmckinley** [comment]
I was not able to find a problem with submitting a survey, but I did find and fix the problem with the other field getting duplicated on pickers on cancel.

**Comment by MatthewGerber** [comment]
Can you pr this if you haven't already? Thanks .
