### ISSUE TITLE
In new version of Sensus for iOS there is no option to add negative value of trigger

### ISSUE THREAD

**Issue by ShabnamWahed** [predictive-technology-laboratory/sensus#556]

**Comment by MatthewGerber** [comment]
I don't know what you mean by "negative value of trigger". Can you please clarify?

**Comment by MatthewGerber** [comment]
I seem to recall an issue with inputting negative numbers in iOS. I don't think we've ever been able to do this properly. I will file this as a bug to be fixed this month. In the meantime, can you try it on Android? It should work there.

**Comment by ShabnamWahed** [comment]
On Android it works fine.
