### ISSUE TITLE
In the process of creating a protocol couldn’t add points of interest

### ISSUE THREAD

**Issue by ikiana** [predictive-technology-laboratory/sensus#566]

**Comment by clmckinley** [comment]
When I try to add a point of interest on my LG G6 I get the google map chrome but the map itself is blank.  
It appears that this might be a problem with the API Key.
The relevant error logs are:

> 08-17 14:22:53.754 D/Mono    ( 3822): Assembly Ref addref Xamarin.Forms.Maps.Android[0x745975f880] -> System.Core[0x7459784600]: 12
> 08-17 14:22:54.177 E/Google Maps Android API( 3822): Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
> 08-17 14:22:54.182 E/Google Maps Android API( 3822): In the Google Developer Console (https://console.developers.google.com)
> 08-17 14:22:54.182 E/Google Maps Android API( 3822): Ensure that the "Google Maps Android API v2" is enabled.
> 08-17 14:22:54.182 E/Google Maps Android API( 3822): Ensure that the following Android Key exists:
