### ISSUE TITLE
Sharing violation on PromoteFiles

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#579]
https://appcenter.ms/orgs/uva-predictive-technology-lab/apps/sensus-android/crashes/errors/1760351121/reports

**Comment by clmckinley** [comment]
I have not been able to reproduce this on my phone.  It looks like it is happening actively (last 15 minutes) on a Pixel 2.  Is that possibly your phone @MatthewGerber ?
