### ISSUE TITLE
Set up Amazon S3 bucket named "sensus/e1".

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#58]
See Wiki for instructions on configuring Amazon S3.

**Comment by trishalaneeraj** [comment]
Fixes #58

**Comment by MatthewGerber** [comment]
Note that, if you do this, you'll need to modify the access policy for the IAM user that Sensus participants will be using to access the S3 bucket. You'll also need to edit the Protocol Form.
