### ISSUE TITLE
Add remaining HealthKit probes

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#585]

**Comment by rd3fa** [comment]
@MatthewGerber I added the HKCharacteristicTypeIdentifier health kit probes (only 5)
But there are 74 HKQuantityTypeIdentifiers. Which ones of those do we want if not all?
 //
    // Summary:
    //     Enumerates the types of HealthKit.HKQuantityType.
    //
    // Remarks:
    //     To be added.
    [global::iOSAttribute(8, 0)]
    [Watch(2, 0)]
    public enum HKQuantityTypeIdentifier
    {
        BodyMassIndex = 0,
        BodyFatPercentage = 1,
        Height = 2,
        BodyMass = 3,
        LeanBodyMass = 4,
        HeartRate = 5,
        StepCount = 6,
        DistanceWalkingRunning = 7,
        DistanceCycling = 8,
        BasalEnergyBurned = 9,
        ActiveEnergyBurned = 10,
        FlightsClimbed = 11,
        NikeFuel = 12,
        OxygenSaturation = 13,
        BloodGlucose = 14,
        BloodPressureSystolic = 15,
        BloodPressureDiastolic = 16,
        BloodAlcoholContent = 17,
        PeripheralPerfusionIndex = 18,
        ForcedVitalCapacity = 19,
        ForcedExpiratoryVolume1 = 20,
        PeakExpiratoryFlowRate = 21,
        NumberOfTimesFallen = 22,
        InhalerUsage = 23,
        RespiratoryRate = 24,
        BodyTemperature = 25,
        DietaryFatTotal = 26,
        DietaryFatPolyunsaturated = 27,
        DietaryFatMonounsaturated = 28,
        DietaryFatSaturated = 29,
        DietaryCholesterol = 30,
        DietarySodium = 31,
        DietaryCarbohydrates = 32,
        DietaryFiber = 33,
        DietarySugar = 34,
        DietaryEnergyConsumed = 35,
        DietaryProtein = 36,
        DietaryVitaminA = 37,
        DietaryVitaminB6 = 38,
        DietaryVitaminB12 = 39,
        DietaryVitaminC = 40,
        DietaryVitaminD = 41,
        DietaryVitaminE = 42,
        DietaryVitaminK = 43,
        DietaryCalcium = 44,
        DietaryIron = 45,
        DietaryThiamin = 46,
        DietaryRiboflavin = 47,
        DietaryNiacin = 48,
        DietaryFolate = 49,
        DietaryBiotin = 50,
        DietaryPantothenicAcid = 51,
        DietaryPhosphorus = 52,
        DietaryIodine = 53,
        DietaryMagnesium = 54,
        DietaryZinc = 55,
        DietarySelenium = 56,
        DietaryCopper = 57,
        DietaryManganese = 58,
        DietaryChromium = 59,
        DietaryMolybdenum = 60,
        DietaryChloride = 61,
        DietaryPotassium = 62,
        DietaryCaffeine = 63,
        BasalBodyTemperature = 64,
        DietaryWater = 65,
        UVExposure = 66,
        ElectrodermalActivity = 67,
        AppleExerciseTime = 68,
        DistanceWheelchair = 69,
        PushCount = 70,
        DistanceSwimming = 71,
        SwimmingStrokeCount = 72,
        WaistCircumference = 73,
        VO2Max = 74
    }

**Comment by MatthewGerber** [comment]
Here's what I would keep.

>
> BodyMassIndex = 0,
> Height = 2,
> HeartRate = 5,
> StepCount = 6,
> DistanceWalkingRunning = 7,
> FlightsClimbed = 11,
> NumberOfTimesFallen = 22,
>
