### ISSUE TITLE
Allow user to pause/sleep sensing from notification.

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#589]

**Comment by MatthewGerber** [comment]
We would like to allow the user to pause/resume data collection at will. Apps like Pandora support pause/resume from the notification tray in Android, and iOS probably supports something similar. Use this approach to provide the user with pause/resume for Sensus.

**Comment by clmckinley** [comment]
Do you see this unloading/loading the protocol or just stopping/starting the probes?
Also, is it a universal switch for all loaded protocols or per protocol?

**Comment by MatthewGerber** [comment]
Just stopping/starting, and for all protocols that are currently running.

Matt
