### ISSUE TITLE
No input for PID on Android.

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#637]
### Which version of Sensus are you currently using?
15.10.0
### Which operating system(s) does this issue involve (Android, iOS, or both)?
Android
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
I don't get a way to enter a PID when I add a study using either QR code or URL.

**Comment by MatthewGerber** [comment]
@Boukhechba What setting are you using for ProtocolStartConfirmationMode?
