### ISSUE TITLE
Add when a survey is responded or expired in the ScriptRunDatum

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#653]

**Comment by MatthewGerber** [comment]
Done. You'll now get instances of [`ScriptStateDatum`](https://predictive-technology-laboratory.github.io/sensus/api/Sensus.Probes.User.Scripts.ScriptStateDatum.html). See the [`State`](https://predictive-technology-laboratory.github.io/sensus/api/Sensus.Probes.User.Scripts.ScriptStateDatum.html#Sensus_Probes_User_Scripts_ScriptStateDatum_State) field and its enumerated type `ScriptState` for details.

This will be available in Sensus 15.12.0.
