### ISSUE TITLE
Protocol Stops by itself Overnight

### ISSUE THREAD

**Issue by rmk4mk** [predictive-technology-laboratory/sensus#688]
### Which version of Sensus are you currently using?
15.12.2
### Which operating system(s) does this issue involve (Android, iOS, or both)?
iOS
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
Whenever I wake up in the morning I find that the sensus protocol has stopped running. Before going to sleep I start the sleep tag and that is the last thing I do in sensus. Then in the morning the protocol has stopped running. Attached are the logs from when I woke up this morning.
[0.txt](https://github.com/predictive-technology-laboratory/sensus/files/2668754/0.txt)

**Comment by MatthewGerber** [comment]
@rmk4mk I did notice a potential problem based on the log you submitted. So I'm keeping this open as a reminder to fix. Let me know if you see it again.

**Comment by rmk4mk** [comment]
It occurred again. Attached are my logs from this morning
[1 (1).txt](https://github.com/predictive-technology-laboratory/sensus/files/2680612/1.1.txt)

**Comment by MatthewGerber** [comment]
Yeah, I saw it too on my device. Working on it.

**Comment by MatthewGerber** [comment]
Version 15.13.0 should help to mitigate this. Installer links forthcoming.
