### ISSUE TITLE
Delete while stopping or starting leaves enrolled notification

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#695]

**Comment by MatthewGerber** [comment]
@clmckinley I noticed that, on Android, if the protocol start-up process takes a while to complete and I delete the protocol before the start-up finishes, then the notification in the tray will show that I am still active in the study after the protocol has been deleted. We need to handle the delete command a bit more carefully, either by interrupting the start-up or waiting for it to finish before stopping/deleting.

**Comment by clmckinley** [comment]
@MatthewGerber I am having trouble reproducing your steps.  What I have tried:
The first thing i did was to create a study with probes that cause the start up to take a while.

Then I
 1) Clicked Start Study but Clicked the Cancel button on the loading screen before it finished starting
- notification to says "You are enrolled in 0 studies"

or

1)  Clicked Start and let it finish
 - Notification says "You are enrolled in 1 study". 
2) Force stop Sensus in the android settings 
3) Launched Sensus again
4) Delete the study before it finishes starting and is in the starting state
 - Notification says "You are enrolled in 0 studies".

**Comment by MatthewGerber** [comment]
@clmckinley Ah, yes...the new start-up progress page will mitigate this problem. I believe there is still one case where this can happen:

1. Create the student you mentioned.
1. Start the study and let the start-up complete.
1. Force-stop Sensus.
1. Open Sensus. Upon opening, Sensus will auto-start the study, which will take some time. During this interval, you should be able to tap the study and select "Delete", thereby reproducing this issue. Let me know if this is true. If so, then the fix might simply be to remove the "Delete" action from the action list, depending on the state of the protocol.

**Comment by clmckinley** [comment]
@MatthewGerber I tested this on the Pixel 2 and my LG G6 and could not reproduce the problem when deleting a starting study.

**Comment by MatthewGerber** [comment]
@clmckinley Closing for now until we see it again. Thanks for trying.
