### ISSUE TITLE
Compass is different on iOS and Android 

### ISSUE THREAD

**Issue by chapman-monroe** [predictive-technology-laboratory/sensus#721]
### Which version of Sensus are you currently using?
The test was run on Sensus version 15.14.0
### Which operating system(s) does this issue involve (Android, iOS, or both)?
both OS
### Describe the bug or enhancement. For bugs, be sure to describe what you were doing in Sensus when the issue occurred, what happened, what you expected to happen, etc.
There appears to be a difference between the compass reporting average on android and iOS

**Comment by MatthewGerber** [comment]
@chapman-monroe It's not possible to assess/fix this without more detail.

**Comment by MatthewGerber** [comment]
@chapman-monroe I believe my email will address this issue. Post back here if you still see discrepancies.
