### ISSUE TITLE
Can't handle MMS in Android

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#75]
MMS are different from SMS:

http://stackoverflow.com/questions/3012287/how-to-read-mms-data-in-android

**Comment by MatthewGerber** [comment]
Note that there is are `android.permission.RECEIVE_SMS` as well as `android.permission.RECEIVE_MMS`...maybe this is why this isn't working?

**Comment by clmckinley** [comment]
The event doesn’t have an id for the MMS messages so the only thing to do is to take the last message.  So to handle the multiple events firing I track the last MMS time that was recorded and don’t record a new mms unless the time changes.  Another complicating factor is that the mms event fires for sms.  This means when the app first loads it could record an old mms message.  To counter this I record the latest mms time on start up.
