### ISSUE TITLE
[High priority] Add visit monitoring to iOS

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#750]
https://developer.apple.com/documentation/corelocation/cllocationmanager/1618692-startmonitoringvisits

**Comment by bzd3y** [comment]
@Boukhechba Should this be a new probe should it be a setting on the Location probes?

**Comment by Boukhechba** [comment]
Yes. This should be a separate iOS-only probe

**Comment by bzd3y** [comment]
@Boukhechba So from what I can read there is no way to debug the visit monitoring functionality. I'm going to have to try testing this manually over the next couple of days because I have no way of knowing if/when it will detect a visit.
