### ISSUE TITLE
[High priority] Add timed snooze

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#779]
@clmckinley @rd3fa We'd like to allow the user to snooze data collection for a window of time. Upon pausing the protocol (either through the Android notification or from within the app by tapping the protocol), ask them how long and then pause for this window.

**Comment by bzd3y** [comment]
@Boukhechba @rd3fa Trying to prepare for this issue. What kind of timeframe are they allowed to snooze and is it by some discrete timespan value (in hours or minutes) or until a certain date/time or both?

**Comment by Boukhechba** [comment]
Good question. Ideally, max snooze time should be a parameter in the protocol, alongside with allow snooze. 
For participants, I think we should let them choose their time frame (minutes, hours, or days), if the value is allowed by the protocol Sensus snoozes data collection, otherwize an error is displayed with the max allowed snooze time.
