### ISSUE TITLE
[High priority] Change Bluetooth probe to discover all near devices  

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#781]
@clmckinley @rd3fa Currently Sensus senses only devices running Sensus with the same protocol. We would like to add a parameter to the Bluetooth probe that let discovering other devices.

**Comment by bzd3y** [comment]
@Boukhechba @rd3fa Should the parameter make the probe discover all devices regardless of whether they are running Sensus or only those that are running Sensus, but with any protocol?

**Comment by Boukhechba** [comment]
@bzd3y We would want that parameter (you can name it discover all) to let sensus discover all devices regardless of whether they run Sensus or not.

**Comment by bzd3y** [comment]
@Boukhechba @rd3fa There are some limitations on iOS related to this issue. The first is that you can't scan for devices not running Sensus in the background. I don't know if it is possible to bring the app to the foreground momentarily to do the scan or not. The second limitation is that it looks like you can only get Bluetooth classic devices that are paired and cannot scan for them.

So it looks like the options are either ignore this setting entirely on iOS or don't and when it is enabled just get paired devices. We can talk about this more in tomorrow's meeting if that would help.

**Comment by Boukhechba** [comment]
Is it the case for BLE ?
