### ISSUE TITLE
[High priority] Correlate phone numbers with contacts list

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#782]
@clmckinley @rd3fa This is mainly to detect of a given phone number collected in SMS or Telephony probes is in the contact list or not.

**Comment by rd3fa** [comment]
@Boukhechba @bzd3y  I have added name. Do we want email as well?

**Comment by Boukhechba** [comment]
@rd3fa if email is available, so yes, that would be interesting.

**Comment by rd3fa** [comment]
@Boukhechba  I have added the email to the sms/telephony probes for android
