### ISSUE TITLE
[High Priority] Add Calendar probe

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#783]

**Comment by bzd3y** [comment]
@Boukhechba @rd3fa Can we get more information on how this probe is supposed to work?

**Comment by Boukhechba** [comment]
@bzd3y  This can be a polling probe (e.g. every day) that collects the calendar events of the previous 24 hours.

**Comment by rd3fa** [comment]
@bzd3y @Boukhechba do we want to add a new category folder under probes for this probe or do we want it to go under any of the existing probe folders?

**Comment by rd3fa** [comment]
@Boukhechba @bzd3y  what information do we want from the events? it looks like this might have to be a listening probe on iOS

**Comment by Boukhechba** [comment]
We should be able to collect any info related to time and description of the event. 
I think this new probe should go under probes/Apps
