### ISSUE TITLE
[High Priority] Add image gallery metadata probe

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#784]

**Comment by bzd3y** [comment]
@Boukhechba @rd3fa Is there any specific metadata that needs to be collected?

**Comment by Boukhechba** [comment]
Time and type of  the event (picture vs. video) and eventually we should store the image/video taken if the "store image/video" parameter is enabled.

**Comment by bzd3y** [comment]
@Boukhechba @rd3fa So it doesn't look like it is possible on iOS to see when a picture has been taken when Sensus isn't in the foreground. Should I just not do an iOS version of this probe or should I try to make it a polling probe (the android one is a listening probe) or make it get the images when Sensus comes to the foreground?

**Comment by Boukhechba** [comment]
With polling we still need the app to be in the foreground to collect this information, right ?
