### ISSUE TITLE
[High priority] Decrease start-up time of surveys

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#796]
@rd3fa @bzd3y Currently there might be a noticeable delay between clicking on a notification to answer a survey and the survey showing up. From our initial testing, it looks like this delay might be caused by the app syncing data to the cloud. We should make Sensus deliver prompt for surveys first than sync data to the cloud.

**Comment by bzd3y** [comment]
@Boukhechba Could you point me to the relevant part of the application for this?

**Comment by Boukhechba** [comment]
@bzd3y Look at Sensus.Shared/UI/PendingScriptsPage.cs

**Comment by bzd3y** [comment]
@Boukhechba Okay, thanks. I looked there but wasn't 100% positive that was it. So is this delay in the list of surveys showing up or is it when the user clicks one of them and it takes a while for it to display the survey? How can I get things in the survey list?

**Comment by bzd3y** [comment]
@Boukhechba Okay, I figured out how to get surveys into the list. Do you have any information on how to reproduce the delay problem?

**Comment by Boukhechba** [comment]
@bzd3y  You can create a protocol that prompts for surveys at specific times. From our testing , it looks like this delay is more pronounced when there is a lot of data to sync. It looks like the app waits until all data is uploaded to S3 than it fires the surveys.

**Comment by rd3fa** [comment]
@Boukhechba  Is this happening only on android? I didn't think you could get survey notifications in the foreground on iOS since the app cannot read the probes to trigger the surveys

**Comment by Boukhechba** [comment]
@rd3fa This is happening mainly on iOS. Those notifications are pushed from the cloud.

**Comment by Boukhechba** [comment]
@bzd3y It looks like the app is waiting for scheduled callbacks to complete
(e.g. Audio poll) before running the scheduled callback that loads the survey. The app attempts to run all overdue callbacks in sequence upon app activation, and the another slow operations might be holding everything up. Solution would be to either:
1- Prioritize the callbacks and run them in priority order (i.e. user interaction callbacks first).
2- Use the [iOS background tasks ](https://developer.apple.com/documentation/backgroundtasks) to update the UI whenever a new Script is scheduled.
