### ISSUE TITLE
[High Priority] Add user initiated surveys 

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#804]
Add test surveys and allow "test surveys" to protocol menu.

**Comment by Boukhechba** [comment]
When allow test surveys is enabled, this will add a "test survey" menu item to the protocol's menu. When clicked, it fire all surveys (scripts) contained in the the protocol.

**Comment by Boukhechba** [comment]
@bzd3y we should name this user initiated surveys. This will allow participants to manually open a survey from a list of available surveys. When allow user initiated surveys is enabled (this should be a parameter for each survey), a menu item will be added to the protocol menu that will allow participants to chose one survey to be fired.

**Comment by bzd3y** [comment]
@Boukhechba Should there still be an option that allows them to initiate all the surveys as well, or only individually?

**Comment by Boukhechba** [comment]
That's a good thought. Having the option of firing all surveys at once is helpful.

**Comment by bzd3y** [comment]
@Boukhechba Okay, I'm not necessarily pushing it. It just looked like the very first thought was about firing all of them for a protocol and then it got changed to firing individually. I'll see how easy it would be to do, though.
