### ISSUE TITLE
[High priority] Add time picker

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#817]
Similar to Datetime picker, but displaying only time.

**Comment by bzd3y** [comment]
@Boukhechba What's the best way to test this? It doesn't look like these inputs are used directly in the UI and I assume get built through reflection when a page is set up or something like that.

**Comment by Boukhechba** [comment]
@bzd3y  did you figure this out ? do you still need my input ?

**Comment by bzd3y** [comment]
@Boukhechba Yep, I figured it out, thanks. I just hadn't gotten back to doing a pull request, but I just did one.
