### ISSUE TITLE
[High Priority] Add app usage probe

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#818]

**Comment by Boukhechba** [comment]
This is very likely that will work only on android

**Comment by bzd3y** [comment]
@Boukhechba We can query for Events and Usage Stats. Events are every time the user does something like foreground an app, background it, etc. Usage Stats are aggregated stats like how long an application was in the foreground, how long it was in the background, the last time it was used, etc.

I assume both could be useful? Should I make two probes or should I try to combine them into one probe? Or only do one of them?
