### ISSUE TITLE
[High Priority] Add accessibility related probes

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#819]
On android, we currently use Accessibility service to collect keystroke data, however there much more that we can do with this service (e.g. gestures, notifications). We would want to add those related probes that will watch for specific events from the accessibility service. See Keystroke probe for reference.

**Comment by bzd3y** [comment]
@Boukhechba Just giving a heads up: I think this is going to require me to refactor the existing keystroke probe to share the accessibility service across all of these probes. Otherwise the system lists a service for each probe which would be confusing and difficult to manage for the user.

**Comment by bzd3y** [comment]
@Boukhechba Also, I noticed that the current keystroke probe captures the entire text as opposed to just the key that was pressed. Is that how it is intended to work? The datum property is named "Key" but it would contain the entire text of the view that changed.

**Comment by bzd3y** [comment]
@Boukhechba What other accessibility data should be collected? There are a bunch of options but I don't know for sure what is useful and how the data needs to be shaped.
