### ISSUE TITLE
[High Priority] fix Bluetooth bugs 

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#820]
@bzd3y It looks like we are experiencing two type of bugs (might be related to each other) when Bluetooth probe is enabled with discover all turned on.

1-The Bluetooth service crashes when Sensus tries to collect this data and the phone is already paired with another device. I tested it with my headphones and the Bluetooth connection is lost each time Sensus searches for Bluetooth signals.

2-Sensus prompts for pairing requests with some devices each time it collects Bluetooth signals

**Comment by bzd3y** [comment]
@Boukhechba are these on iOS, Android or both?

**Comment by bzd3y** [comment]
@Boukhechba Is this "discover all" to also scan for things not running sensus, or is the "all" indicate that it is scanning for both Bluetooth and btle?

**Comment by bzd3y** [comment]
I'm leaving a note that I'm putting this on pause until there's more information on what might be happening.

**Comment by Boukhechba** [comment]
@bzd3y  This has been observed only on Android. The discover all intends to scan for things not running sensus.
