### ISSUE TITLE
Restructure the recently added probes and datums

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#852]
@bzd3y  I noticed that the recently added probes and datums such as imagemetadata and app usage don't follow the same structure as our previous classes. Please make sure to follow the same logic. For instance, set getters and setters for all classes. Declare the probe as abstract in Sensus.shared and implement it on Sensus.Android and Sensus.Shared if any. Also make sure, displaydetail and placeholder methods are populated. It would also be good to include documentations (comment with ///) as much as possible to describe the probe/datum and their parameters. See AccelerationProbe for reference.

**Comment by bzd3y** [comment]
@Boukhechba Okay, what do you mean by "set getters and setters for all classes"? Do you mean just make sure each property has getters and setters?

**Comment by bzd3y** [comment]
@Boukhechba The ImageMetadata probe project/namespace structure seems to match the pattern of the other probes. Does something need to change there or does it just need documentation comments?

**Comment by Boukhechba** [comment]
No they are fine. Thanks.

**Comment by bzd3y** [comment]
@Boukhechba So do you want no expression body properties in the probes and datums or only when there is both a getter and a setter?

**Comment by bzd3y** [comment]
@Boukhechba Ignore my last question, it looks like everything else uses block body, so I'll make it all consistent.
