### ISSUE TITLE
Improve app permission requests loading 

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#878]

**Comment by bzd3y** [comment]
@Boukhechba What is the best way to cancel the protocol start if the user doesn't give permission? Call StopAsync() on the protocol? Or should I try to use the cancellation token from the start process ? Currently that is completely internal to the protocol.

**Comment by Boukhechba** [comment]
@bzd3y  I am not sure if StopAsync() will work, because by that time, the protocol's state will still be "stopped".  Maybe you can give it a try.
