### ISSUE TITLE
FB probe with fresh FB app

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#88]
On a freshly wiped Android/iOS device, first install the Facebook app, then install Sensus and create a protocol with the FacebookProbe enabled. Does the Facebook authentication/authorization process work properly when the protocol is started?

**Comment by trishalaneeraj** [comment]
Yes. After the protocol is started, the Facebook login page appears only once, and not repeatedly, as was the case before. Since, I did not want to clutter S3 with a new protocol, I ran E2v1 for this purpose.
