### ISSUE TITLE
Fix System.ArgumentOutOfRangeException in Crash Group # 626877309u

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#886]
### Reason ###

System.ArgumentOutOfRangeException

### Link to App Center ###

* [https://appcenter.ms/orgs/uva-predictive-technology-lab/apps/sensus-iOS-1/crashes/errors/626877309u](https://appcenter.ms/orgs/uva-predictive-technology-lab/apps/sensus-iOS-1/crashes/errors/626877309u)

**Comment by bzd3y** [comment]
@Boukhechba I think I might have a fix for this. I think the DistantPast and/or DistantFuture dates in iOS are causing problems with .NET DateTime values. I've fixed the code and I'll test it today and over the weekend to try to get a visit to register.
