### ISSUE TITLE
Add regex-based anonymisation

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#893]
Add a new anonymisation method to omit/hash only characters targeted by a regex expression.

**Comment by bzd3y** [comment]
@Boukhechba I have a couple questions to make sure I implement this correctly:

Is this a new anonymizer or an option on existing anonymizers to only apply the anonymization when the regex is matched?

Does it anonymize the entire value when there is a match or is it anonymizing just the matches within the value? Or should that be configurable?

Should it be configurable as to whether the value is omitted or hashed or should I just do whichever is the easiest?
