### ISSUE TITLE
Sensus.Exceptions.SensusException: Received null PNR protocol.

### ISSUE THREAD

**Issue by Boukhechba** [predictive-technology-laboratory/sensus#896]
https://appcenter.ms/orgs/uva-predictive-technology-lab/apps/sensus-iOS-1/crashes/errors/780296503/overview

**Comment by bzd3y** [comment]
@Boukhechba This appears to be when the app attempts to cancel notifications, like when using a timer-based callback scheduler. Notifications for callbacks associated with things like the health tests and probably anything that doesn't have a protocol will throw this error.
