### ISSUE TITLE
Background Tasks for iOS 13+

### ISSUE THREAD

**Issue by bzd3y** [predictive-technology-laboratory/sensus#899]

**Comment by bzd3y** [comment]
@Boukhechba These tasks are identified by a string. For an initial implementation I figured I could use ScheduledCallback.Id for the BackgroundTask identifier. After looking into things more, it looks like these identifiers have to be registered in Info.plist and have to be unique.

**Comment by bzd3y** [comment]
@Boukhechba I don't think these will work for Sensus, at least not for things like polling or other callbacks that have to run at a specific time. You can't control when the background task is run and from what I read it could take hours before the phone decides to run it.

**Comment by Boukhechba** [comment]
@bzd3y Thanks. We will think about how to leverage it later.
