### ISSUE TITLE
Fix protocol open bug

### ISSUE THREAD

**Issue by MatthewGerber** [predictive-technology-laboratory/sensus#90]
When opening from Downloads folder on Android, permissions might be denied (Wes's phone) or the file might not be associated with Sensus (Marcus's phone). Both need to be fixed.

**Comment by MatthewGerber** [comment]
While opening the point of interest page, Sensus tried to log into facebook and that failed which caused a crash. (Marcus)

**Comment by MatthewGerber** [comment]
On Samsung Note, downloading email attachment and then opening does not work. Are the appropriate filters set up for this?

**Comment by cadancai** [comment]
I met with Trishaw yesterday and it seems I have the same problem. My phone is an amazon fire phone, but the system is the cyanogenMod 11.

**Comment by MatthewGerber** [comment]
http://stackoverflow.com/questions/3760276/android-intent-filter-associate-app-with-file-extension
